### ISSUE TITLE
Exception while updating neighbours

### ISSUE THREAD

**Issue by MegaFlary** [Deadrik/TFCraft#798] opened 2015-08-23 12:06 UTC
Currently using latest dev commit.
https://paste.ee/p/xZ4Y4

**Comment by Kittychanley** [comment] 2015-08-23 16:17
#582 

I'm assuming you chopped down a large sequoia tree, or a tree in a very dense forest when this happened. This is a very old bug, and definitely not one caused by a recent commit. It has also be marked as "won't fix" in the official bug list.

**Closed by Kittychanley** 2015-08-23 16:17 UTC
